name: Compile

on:
 workflow_dispatch:
 schedule:
 - cron: '01 21 * * *'

jobs:
 compile_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz

    - name: Run script
      run: python alina-lang-transformer.py

    - name: Commit and push new XML file
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit --allow-empty -m "Update XML file"
        git fetch origin main
        git merge origin/main
        git push

    - name: Extract Date from File Name
      id: extract_date
      run: |
        FILE_NAME=$(ls eliteng_*.xml | head -n 1)
        DATE=$(echo $FILE_NAME | sed -n 's/eliteng_\(.*\).xml/\1/p')
        echo "DATE=$DATE" >> $GITHUB_ENV

    - name: Rename XML file
      run: |
        mv ${{ env.FILE_NAME }} eliteng.xml

    - name: Create Release and Upload XML Files
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.DATE }}
        files: eliteng.xml
