name: Compile

on:
 workflow_dispatch:
    schedule:
      - cron: '01 21 * * *'

jobs:
 compile_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz

    - name: Run script
      run: python alina-lang-transformer.py

    - name: Commit and push new XML file
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update XML file"
        git push

    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - XML file updated
        draft: false
        prerelease: false
