name: Compile

on:
 workflow_dispatch: # This allows the workflow to be triggered manually.
 schedule:
    - cron: '*/5 * * * *' # This runs the workflow every 5 minutes.

jobs:
 compile_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run script
      run: python alina-lang-transformer.py

    - name: Commit and push new XML file
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update XML file"
        git push
